feat(.github): simplify test and deployment (#162)
<!-- markdownlint-disable first-line-heading -->

## Summary

This pull request includes several changes to the GitHub Actions
workflows and the pull request template. The most important changes
involve the restructuring of the workflows to streamline the CI/CD
process and the reorganization of the pull request template for better
clarity.

### Workflow Changes:

* **New CI Workflow**: Introduced a new workflow named `[♻️] test and
lint` to handle linting, testing, and building of affected applications.
This workflow includes steps for checking out the code, installing
dependencies, and publishing coverage reports.
(`.github/workflows/_workflow.jobs.ci.yml`)
* **Removed Unused Workflows**: Deleted several outdated workflows,
including `clean_pull_request`, `infra`, `lint_test_build_affected`, and
`post_deploy` workflows, to simplify the CI/CD configuration.
(`.github/workflows/_workflow.jobs.clean_pull_request.yml`)
[[1]](diffhunk://#diff-ddb4ef1642ab0378d91aa7c7399458d2515fcb2687020a3f4119cc776ed86298L1-L55)
(`.github/workflows/_workflow.jobs.infra.yml`)
[[2]](diffhunk://#diff-1687a35e60f448a5c9713b8f9c823ff5abf3fc261640be192f6cccd309c65370L1-L125)
(`.github/workflows/_workflow.jobs.lint_test_build_affected.yml`)
[[3]](diffhunk://#diff-cdb422b74116b5f450812cad85de2fa1687de2cccba3cc286fd6b895b9ec91a3L1-L157)
(`.github/workflows/_workflow.jobs.post_deploy.yml`)
[[4]](diffhunk://#diff-0f1b019d22a46726baed61a1c76b81a1a2c691b4432322d9c6ded50fda62796cL1-L100)

### Pull Request Template Changes:

* **Reorganized Template**: Updated the pull request template to improve
clarity by renaming the "Summary" section to "Details" and rearranging
sections for better readability. (`.github/PULL_REQUEST_TEMPLATE.md`)
[[1]](diffhunk://#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35L3-R5)
[[2]](diffhunk://#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35L28-L34)
[[3]](diffhunk://#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35R24-R30)

### Dependency Management:

* **Simplified Dependency Installation**: Replaced the manual dependency
installation steps with a reusable action `chill-viking/npm-ci` to
streamline the setup process.
(`.github/actions/install-deps/action.yml`)

## Checklist

- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my
feature works

<!-- Additional details -->
<details>
<summary><strong>Expand for additional details</strong></summary>

## Screenshots

<!--
If the changes are visual, including screenshots or GIFs can
help reviewers understand them more easily.
-->

## Related issues

#161 

## Testing instructions

<!--
Instructions on how to test the changes made in the pull
request, helping reviewers validate the code.
-->

</details>
<!-- End of Additional details -->

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -19,157 +19,51 @@ permissions:
   security-events: write
 
 jobs:
-  # prepare the deployment parameters
-  prep:
-    name: '🛠️'
-    uses: './.github/workflows/_workflow.jobs.preparation.yml'
-    with:
-      bicep_main_file: './.biceps/main.bicep'
-      resource_group: 'blog-rg'
-      location: 'westeurope'
-      app_name: 'blog'
-      branch_name: ${{ github.head_ref || github.ref_name }}
-
-  # lint, test, and build the blog application
+  # lint and test all affected
   lint_test_build:
     if: |
       (github.event_name == 'pull_request' && github.event.action != 'closed') ||
       (github.event_name == 'push' && github.ref == 'refs/heads/main')
-    name: '🧪 | 🏗️'
+    name: '🧪 & 🧹️'
+    uses: './.github/workflows/_workflow.jobs.ci.yml'
+    secrets: inherit
+
+  # build and deploy blog
+  build_deploy_blog:
+    name: '🏗️ Blog 🚀'
+    uses: './.github/workflows/_workflow.jobs.cd.yml'
     needs:
-      - prep
-    uses: './.github/workflows/_workflow.jobs.lint_test_build_affected.yml'
+      - lint_test_build
     with:
       project_name: 'blog'
+      resource_group: 'blog-rg'
       build_location: 'dist/apps/blog'
-      infra_affected: ${{ needs.prep.outputs.infra_affected }}
-      project_affected: ${{ needs.prep.outputs.app_affected }}
-      nx_base: ${{ needs.prep.outputs.nx_base }}
-    secrets: inherit
-
-  # deploy static web app using /.biceps/main.bicep
-  infra:
-    if: |
-      (github.event_name == 'pull_request' && github.event.action != 'closed') ||
-      (github.event_name == 'push' && github.ref == 'refs/heads/main')
-    name: '🏭'
-    needs:
-      - prep
-    uses: './.github/workflows/_workflow.jobs.infra.yml'
-    with:
-      parameters: ${{ needs.prep.outputs.parameters }}
-      app_name: ${{ needs.prep.outputs.app_name }}
-      bicep_main_file: ${{ needs.prep.outputs.bicep_main_file }}
-      infra_affected: ${{ needs.prep.outputs.infra_affected }}
-    secrets: inherit
-
-  # deploy the blog application
-  deploy_app:
-    needs:
-      - prep
-      - lint_test_build
-      - infra
-    if: |
-      always() &&
-      (needs.prep.outputs.infra_affected == 'No' || needs.infra.result == 'success') &&
-      needs.lint_test_build.result == 'success' &&
-      needs.lint_test_build.outputs.uploaded_artifacts == 'Yes' &&
-      github.event.action != 'closed'
-    runs-on: ubuntu-latest
-    name: 'Deploy app 🚀'
-    steps:
-      - name: 'AZ CLI login 🔑'
-        uses: azure/login@v2
-        with:
-          client-id: ${{ secrets.AZURE_CLIENT_ID }}
-          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-
-      - name: 'Get API key 🔑'
-        id: static_web_app_apikey
-        uses: azure/CLI@v2
-        with:
-          azcliversion: '2.63.0' # remove after jq is available in the default version
-          inlineScript: |
-            apiKey=$(az staticwebapp secrets list \
-              --name '${{ needs.prep.outputs.app_name }}-static-web-app' \
-              | jq -r '.properties.apiKey')
-            echo "api_key=$apiKey" >> $GITHUB_OUTPUT
-
-      - name: 'Download artifacts 📥'
-        uses: actions/download-artifact@v4
-        with:
-          name: compiled-app
-          path: dist
-
-      - name: 'Publish SWA 🚀'
-        id: publish_swa
-        uses: azure/static-web-apps-deploy@v1
-        if: steps.static_web_app_apikey.outputs.api_key != ''
-        with:
-          azure_static_web_apps_api_token: ${{ steps.static_web_app_apikey.outputs.api_key }}
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          action: 'upload'
-          app_location: 'dist/browser'
-          api_location: '' # Empty for now, no API to deploy
-          skip_app_build: true
-    outputs:
-      deployed_url: ${{ steps.publish_swa.outputs.static_web_app_url }}
-
-  # clean up the staging deployment
-  clean_pull_request:
-    if: github.event_name == 'pull_request' && github.event.action == 'closed'
-    uses: './.github/workflows/_workflow.jobs.clean_pull_request.yml'
-    name: '🧹'
-    needs:
-      - prep
-    with:
-      app_name: ${{ needs.prep.outputs.app_name }}
-    secrets: inherit
-
-  # run post deployment checks
-  post_deploy:
-    uses: './.github/workflows/_workflow.jobs.post_deploy.yml'
-    name: '🧪 🚀'
-    needs:
-      - deploy_app
-    if: |
-      always() &&
-      needs.deploy_app.result == 'success' &&
-      github.event.action != 'closed'
-    with:
-      deployment_url: ${{ needs.deploy_app.outputs.deployed_url }}
       audit_urls: |
-        ${{ needs.deploy_app.outputs.deployed_url }}/
-        ${{ needs.deploy_app.outputs.deployed_url }}/about-me
-        ${{ needs.deploy_app.outputs.deployed_url }}/development-notes
-        ${{ needs.deploy_app.outputs.deployed_url }}/not/found
+        /
+        /about-me
+        /development-notes
+        /not/found
+    secrets: inherit
 
   ci_status:
     name: 'CI Status ✅'
     runs-on: ubuntu-latest
     needs:
       - lint_test_build
-      - infra
-      - deploy_app
-      - post_deploy
+      - build_deploy_blog
     if: always()
     steps:
       - name: 'lint_test_build failed'
         if: needs.lint_test_build.result == 'failure'
-        run: exit 1
+        run: |
+          echo "::error::lint_test_build failed"
+          exit 1
 
-      - name: 'infra failed'
-        if: needs.infra.result == 'failure'
-        run: exit 1
-
-      - name: 'deploy_app failed'
-        if: needs.deploy_app.result == 'failure'
-        run: exit 1
-
-      - name: 'post_deploy failed'
-        if: needs.post_deploy.result == 'failure'
-        run: exit 1
+      - name: 'build_deploy_blog failed'
+        if: needs.build_deploy_blog.result == 'failure'
+        run: |
+          echo "::error::build_deploy_blog failed"
+          exit 1
 
       - name: 'checks completed'
         run: echo "All checks done"
